name: Tarea Automatizada de ejecución de pruebas

env:
  SONAR_ORG: 'bczlopezcatunta'                  # Nombre de la organización en SonarCloud
  SONAR_PROJECT: 'bczlopezcatunta_bddreportes'   # Key ID del proyecto en SonarCloud

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Ajusta la versión de PHP según tus necesidades
        extensions: mbstring, intl, pdo_mysql

    - name: Install Composer dependencies
      run: composer install

    - name: Create reports directory
      run: mkdir -p features/bootstrap/reports



    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Upload Behat HTML report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: behat-report
        path: features/bootstrap/reports/index.html

 